# Generated by Django 2.2.6 on 2020-01-05 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20191226_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='stater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
